nocode:
  master:
     db:
       mongo:
         host: localhost
         port: 27017
         database: master
         authenticationDatabase: admin
         username: root
         password: kiran@123